[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "Clapping Asynchronously (CLI Applications With Futures)"

[preprocessor.graphviz]
command = "mdbook-graphviz"
